container:
  image: golang:latest
  cpu: 8
  memory: 32G

task:
  install_wget_script: apt-get update && apt-get install wget
  env:
    CGO_ENABLED: "0"

  matrix:
    - name: "russia"
      env:
        MAP: "russia"

    - name: "europe"
      env:
        MAP: "europe"

    - name: "north-america"
      env:
        MAP: "north-america"

    - name: "south-america"
      env:
        MAP: "south-america"

  map_cache:
    folder: map
    fingerprint_script: echo $MAP
    reupload_on_changes: "true"
    populate_script: |
      mkdir map && cd map
      wget -N "https://download.geofabrik.de/${MAP}-latest.osm.pbf"

  generate_script: |
    CGO_ENABLED=0 go run ./cmd/main.go generate -i ./map/${MAP}-latest.osm.pbf -p ./$MAP -c /tmp/geocache

  upload_artifacts:
    path: $MAP.gob.zstd
