container:
  image: golang:latest
  ram: 32Gb

task:
  install_wget_script: apt-get update && apt-get install wget
  matrix:
    - name: "russia"
      env:
        MAP: "russia"
    - name: "europe"
      env:
        MAP: "north-america"
    - name: "russia"
      env:
        MAP: "north-america"
    - name: "south-america"
      env:
        MAP: "south-america"

  map_cache:
    folder: map
    fingerprint_script: echo $MAP
    reupload_on_changes: "true"
    populate_script: |
      mkdir map && cd map
      wget -N "https://download.geofabrik.de/${MAP}-latest.osm.pbf"
