build_task:
  container:
    image: golang:latest

  env:
    CGO_ENABLED: "0"

  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod

  get_script: go get ./...

  build_script: go build -o geocache-$OS ./cmd/main.go

  binaries_artifacts:
    path: geocache-$OS

generate_points_task:
  container:
    image: golang:latest
    cpu: 8
    memory: 32G
  skip: "!changesInclude('.cirrus.yml', 'geoparser/**', 'geomodel/**', 'kv/**', 'cmd/**')"

  install_deps_script: apt-get update && apt-get install wget

  matrix:
    - name: "post-cis"
      env:
        MAPS: "europe/ukraine,russia,europe/belarus,europe/finland,europe/georgia,asia/afghanistan,asia/armenia,asia/azerbaijan,asia/kazakhstan,asia/uzbekistan,asia/mongolia"

  map_cache:
    folder: maps
    populate_script: |
      mkdir maps && cd maps
      export IFS=","
      for map in $MAPS; do
        wget -N "https://download.geofabrik.de/${map}-latest.osm.pbf"
      done

  generate_script: |
    $MAPS_FILES=""
    for map in $MAPS; do
      $MAPS_FILES="%{MAPS},maps/${map}-latest.osm.pbf"
    done
    go run ./cmd/main.go generate -i $MAPS_FILES -p ./${CIRRUS_TASK_NAME}_points

  upload_artifacts:
    path: ${CIRRUS_TASK_NAME}_points.gob.zstd
